# Generated by Django 4.1.5 on 2023-01-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=254)),
                ('fiscal_num', models.IntegerField()),
                ('reference', models.IntegerField()),
                ('purchase_num', models.IntegerField()),
                ('payment_days', models.CharField(choices=[('1', 'Immediate'), ('2', '30 Days'), ('3', '60 Days'), ('4', '120 Days')], max_length=1)),
                ('type_vat', models.CharField(choices=[('1', 'Intermédio (13%)'), ('2', 'Isento de IVA'), ('3', 'IVA Autoliquidação'), ('4', 'Normal (23%)'), ('5', 'Reduzida (6%)')], max_length=1)),
                ('project_value', models.IntegerField()),
                ('hour_value', models.IntegerField()),
                ('extra_costs', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='code1',
            field=models.CharField(default='MCAAL', max_length=5),
        ),
        migrations.AddField(
            model_name='project',
            name='code2',
            field=models.CharField(default='EAS1', max_length=4),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_time',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='project',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_external',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_rd',
            field=models.CharField(default=1, max_length=1, verbose_name='Is it research and development project ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='long_time',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='project',
            name='night_time',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='project',
            name='payment',
            field=models.CharField(choices=[('1', 'Current account'), ('2', 'Fixed cost 30'), ('3', 'Fixed cost 50'), ('4', 'Fixed cost 100'), ('5', 'Not billable')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Not started'), ('2', 'Ongoing'), ('3', 'Completed')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='travel_time',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('1', 'External project'), ('2', 'Commencement driver assignment'), ('3', 'Current accoutn'), ('4', 'Internal project'), ('5', 'Internal assignment'), ('6', 'Master thesis'), ('7', 'Service Ongoing'), ('8', 'Short-term leave of absence skills development')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('1', 'Visible only to the member of the project'), ('2', 'Visible to everyone')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='weekend_time',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
