# Generated by Django 4.2.3 on 2023-07-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_is_rd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group_id',
        ),
    ]
