# Generated by Django 4.2.3 on 2023-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='code2',
            field=models.CharField(max_length=4),
        ),
    ]
