# Generated by Django 4.2.3 on 2023-07-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fiscal_num',
            new_name='tax_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='code',
        ),
        migrations.AlterField(
            model_name='client',
            name='extra_costs',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='hour_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='project_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
